### ISSUE TITLE
Issue with the initial steady state simulation 

### ISSUE THREAD

**Issue by richpaulcol** [glorialulu/wmoc#1]
* tsnet version: 0.1.0
* Python version: 3.7.3
* Operating System: Ubuntu 19.04

### Description
Trying to run a single pipe model created in EPANET2, 
Reservoir - Pipe - Junction (with Demand)

### What I Did
Isn't able to solve the initial conditions.  From exploring things it looks like it is an issue with the WNTR solver.  If I use wntr.sim.EpanetSimulator I can get steady state results.

Suggest reinstating the option of using the WNTR.EpanetSimulator  as a steady state option

Code
#Open an example network and create a transient model
inp_file = 'Projects/SinglePipe/SinglePipe.inp'
tm = tsnet.network.TransientModel(inp_file)
# Set wavespeed
tm.set_wavespeed(100.) # m/s
# Set time options
tf = 60   # simulation period [s]
tm.set_time(tf)
# Initialize steady state simulation
t0 = 0. # initialize the simulation at 0 [s]
engine = 'DD' # demand driven simulator
tm = tsnet.simulation.Initializer(tm, t0, engine)

Output
Simulation time step 5.00000 s
Total Time Step in this simulation 12
/usr/local/lib/python3.7/dist-packages/tsnet-0.1.0-py3.7.egg/tsnet/simulation/initialize.py:176: RuntimeWarning:

invalid value encountered in sqrt

/usr/local/lib/python3.7/dist-packages/tsnet-0.1.0-py3.7.egg/tsnet/simulation/initialize.py:130: RuntimeWarning:

invalid value encountered in sqrt

/usr/local/lib/python3.7/dist-packages/tsnet-0.1.0-py3.7.egg/tsnet/simulation/initialize.py:131: RuntimeWarning:

invalid value encountered in sqrt

/usr/local/lib/python3.7/dist-packages/tsnet-0.1.0-py3.7.egg/tsnet/simulation/initialize.py:213: UserWarning:

1 :the friction coefficient 9582331419.0118 is too large.                         The D-W coeff has been set to 0.03

**Comment by richpaulcol** [comment]
Having done a little more testing the WNTR model works for H-W friction but not D-W friction.

**Comment by glorialulu** [comment]
Hi Richard, 
It seems to be an issue with WNTR. EPANET has been used instead as the demand-driven simulator for initial conditions.
