### ISSUE TITLE
Initial simulation time (seconds)

### ISSUE THREAD

**Issue by shenh** [glorialulu/wmoc#11]
Could you confirm the meaning of the initial simulation time (t0) in the code snippet below:
```
# Initialize steady state simulation
t0 = 0. # initialize the simulation at 0s
engine = 'DD' # or PPD
tm = tsnet.simulation.Initializer(tm, t0, engine)
```
By looking into the code, it seems t0 must be an integer time of EPANET reporting step. For example, if the reporting time step is 30 minutes, this initial time t0 can be 0, 1800, 3600, 5400, etc. 

Thanks,

Hailiang

**Comment by glorialulu** [comment]
Yes, you are right. t0 is the time that you want to start the transient. The steady-state results at t0 will be used as the initial conditions in the transient simulation.
