### ISSUE TITLE
TransientModel

### ISSUE THREAD

**Issue by chocolate-771** [glorialulu/wmoc#13]
Hello, how do you understand that N in set_time_N is ‘Number of segments in the critical pipe’?

**Comment by glorialulu** [comment]
Please refer to our documentation about the choice of time step [https://tsnet.readthedocs.io/en/latest/transient.html#choice-of-time-step](https://tsnet.readthedocs.io/en/latest/transient.html#choice-of-time-step).

**Comment by chocolate-771** [comment]
Thank you for your reply , I got it .
