### ISSUE TITLE
Pressure-driven Demand

### ISSUE THREAD

**Issue by chocolate-771** [glorialulu/wmoc#14]
* tsnet version:  latest master
* Python version: 3.7
* Operating System: windows

### Description
During the transient simulation in TSNet, the demands are treated as pressure-dependent discharge. The actual demands will vary from the demands defined in the INP file, why not use the same hydraulic equation? What are the considerations for this?

According to the formula in https://tsnet.readthedocs.io/en/latest/transient.html, if the pressure increases, the flow rate will continue to increase. However, the node requirements at the beginning have been determined. After the node pressure exceeds the required pressure, shouldn't the node flow rate remain unchanged?

Pressure dependent demand  the formula in wntr

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">   <mtable columnalign="right left" rowspacing="3pt" columnspacing="0em" displaystyle="true">     <mtr>       <mtd>         <mi>d</mi>         <mo>=</mo>         <mrow>           <mo>{</mo>           <mtable columnalign="left left" rowspacing=".2em" columnspacing="1em" displaystyle="false">             <mtr>               <mtd>                 <mn>0</mn>               </mtd>               <mtd>                 <mi>p</mi>                 <mo>&#x2264;</mo>                 <msub>                   <mi>P</mi>                   <mn>0</mn>                 </msub>               </mtd>             </mtr>             <mtr>               <mtd>                 <msub>                   <mi>D</mi>                   <mi>f</mi>                 </msub>                 <mo stretchy="false">(</mo>                 <mfrac>                   <mrow>                     <mi>p</mi>                     <mo>&#x2212;</mo>                     <msub>                       <mi>P</mi>                       <mn>0</mn>                     </msub>                   </mrow>                   <mrow>                     <msub>                       <mi>P</mi>                       <mi>f</mi>                     </msub>                     <mo>&#x2212;</mo>                     <msub>                       <mi>P</mi>                       <mn>0</mn>                     </msub>                   </mrow>                 </mfrac>                 <msup>                   <mo stretchy="false">)</mo>                   <mrow class="MJX-TeXAtom-ORD">                     <mn>1</mn>                     <mrow class="MJX-TeXAtom-ORD">                       <mo>/</mo>                     </mrow>                     <mi>e</mi>                   </mrow>                 </msup>               </mtd>               <mtd>                 <msub>                   <mi>P</mi>                   <mn>0</mn>                 </msub>                 <mo>&#x2264;</mo>                 <mi>p</mi>                 <mo>&#x2264;</mo>                 <msub>                   <mi>P</mi>                   <mi>f</mi>                 </msub>               </mtd>             </mtr>             <mtr>               <mtd>                 <msub>                   <mi>D</mi>                   <mi>f</mi>                 </msub>               </mtd>               <mtd>                 <mi>p</mi>                 <mo>&#x2265;</mo>                 <msub>                   <mi>P</mi>                   <mi>f</mi>                 </msub>               </mtd>             </mtr>           </mtable>           <mo fence="true" stretchy="true" symmetric="true"></mo>         </mrow>       </mtd>     </mtr>   </mtable> </math>
--

--
Pressure dependent demand  the formula in TSNet：
<img src="https://render.githubusercontent.com/render/math?math=d_{actual} = k \sqrt{H_p}">
--
<img src="https://render.githubusercontent.com/render/math?math=d_{actual} = k = \frac{d_0}{\sqrt{{H_p}_0}}">

--

**Comment by glorialulu** [comment]
In the initial condition calculation, the pressure-driven demands are calculated as WNTR defined.

During transient simulation, the demands are instantaneous. It is kinda like assuming that the faucet is open; thus, when the pressure is high, the demand is proportionally high and it is possible that actual instantaneous demand exceeds required demand. It should be noted that the time scale during transient simulation is much smaller than that during extended-period simulation (EPS).

**Comment by chocolate-771** [comment]
Thank you for your reply，I get it.
