### ISSUE TITLE
Custom pressure driven demands, leaks and no leaks setup.

### ISSUE THREAD

**Issue by IDoytchinov** [glorialulu/wmoc#17]
* tsnet version: 0.2.2
* Python version: 3.9
* Operating System: Linux

### Description

Dear all, we trying to use TSnet to create (random or designer chosen) user demand pulse patterns https://tsnet.readthedocs.io/en/latest/transient.html#demand-pulse (using a function to create desired waveform) on some nodes driving the hydraulic network, no leaks and no demands on another set of nodes and constant pressure driven leaks on 3rd set of nodes in a distributed network. We are not sure how to set-up the simulation accordingly. Is it true that when we use 'demand pulse' function with some custom waveform it will be still pressure/head driven with Q= k*sqrt(Hp local)? As well how should we set our EPANET .ipn in order to make this work right? Not sure if we set everything to zero would work as I guess you use the .ipn file for initial k constant calculation? As well do we need to select PDD (pressure de) instead of DD? Thanks a lot for the help and clarification!

Thanks a lot for your help and advice!

Iordan Doytchinov

**Comment by IDoytchinov** [comment]
One more question: are customer demand pulses still pressure-driven or are they forcing the system to a particular demand?? Thus the only way to get a custom pressure-driven demand is trough modifying the burst coefficient? Thanks a lot for clarifying! :)

**Comment by glorialulu** [comment]
Hi Iordan,

To begin with, I want to clarify that all demands in TSNet pressure-driven with Q = k*sqrt(H_p).

To a typical demand node, the k is calculated from the initial head condition (H_0) and the demand specified in .INP file by
k = demand/sqrt(H_0). More details can be found [here](https://tsnet.readthedocs.io/en/latest/transient.html#pressure-driven-demand)

For nodes with demand pulse, k changes with time. We assume that the amplitude of a demand pulse (𝑝𝑎(𝑡)) follows a symmetrical trapezoidal time-domain function, as detailed [here](https://tsnet.readthedocs.io/en/latest/transient.html#demand-pulse).
The demand specified in .INP file offers a base k_0, such that the changing k for demand pulse is 𝑘(𝑡)=𝑘0+𝑘0×𝑝𝑎(𝑡).

Hope this makes sense.

Best,
Lu

**Comment by IDoytchinov** [comment]
Thank you for the feedback Lu. Thus we can accept that if we use a demand pulse Qdp= k(t)*sqrt(H_p) where k(t) =𝑘0+𝑘0×𝑝𝑎(𝑡)?
In the same way, if we want to use the burst Qbirst = k(b)*sqrt(H_p) where the k(b) = f(t) and could be starting at any time we select it to? Thus if we want to design a Pressure Dependent F(Hp) custom burst (sinusoidal form for example) we can either use the demand pulse or burst and make sure we design k(f(x)) well?

Thanks a lot for confirming! We just want to make sure our custom burst/leaks/demands are f(H_p) local! All the best,

Iordan

**Comment by glorialulu** [comment]
You are right. The equations behind burst and demand pulse are all in the form of Q=k*sqrt(H).
They differ in the way k changes over time. As long as you make sure you define k(t) the way you want to do it, you should be fine.

Best,
Lu
