### ISSUE TITLE
Water flow direction

### ISSUE THREAD

**Issue by IDoytchinov** [glorialulu/wmoc#18]
* tsnet version:
* Python version:
* Operating System:

### Description

 Hello, we were wondering how to know the absolute flow direction for each pipe within a pipe network system? We guess that if the flow velocity goes negative during simulation then the direction of the water flow direction has shifted? As well if we have a positive velocity how do we know the original direction of the water in a meshed system? Assuming we have a water tank and water network on the same level? 

Thanks a lot for your help and advice!

Iordan D

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by glorialulu** [comment]
Hi Iordan, 

To answer  your questions:

1. The positive flow directions are determined by the pipe definition in the .INP file. For example, if pipe1 starts at node1 and ends at node2, then the positive direction is from node1 to node2, and the negative flow direction is from node2 to node1. 
2. yes, when the flow results exhibit a negative sign, the flow direction is negative, as explained in 1.

**Comment by IDoytchinov** [comment]
Thanks for the clarification @glorialulu ! :)
