### ISSUE TITLE
Single Pipe Simulations

### ISSUE THREAD

**Issue by richpaulcol** [glorialulu/wmoc#2]
* tsnet version: 0.1.0
* Python version: 3.7.3
* Operating System: Ubuntu 19.04

### Description
Simulations with a single pipeline fail.
The same physical system but split into 2 pipe sections appears to work.

I don't think this is a big concern but I can't work out why the issue appears

I am Including  python tester file and the two scenarios tested in .inp format in the zip file

[issue.zip](https://github.com/glorialulu/TSNet/files/4064826/issue.zip)

**Comment by glorialulu** [comment]
Hi,
Thanks for pointing the bug. It has been fixed. 
1. Epanet simulator used for demand driven simulation
2. single pipe bug fixed
