### ISSUE TITLE
Total head VS Pressure head

### ISSUE THREAD

**Issue by IDoytchinov** [glorialulu/wmoc#20]
### Description

 Hello, just a simple question. The output 'head' from TSnet is in fact the Pressure head of the system?
(https://www.thermal-engineering.org/what-is-hydraulic-head-definition/) and not the total head equal to the sum of the Pressure head, Velocity head and Elevation head?  Thanks a lot for the clarification!

Best,

Iordan

**Comment by glorialulu** [comment]
Hi Iordan, 

The head results refer to the piezometric head (pressure head + elevation).

**Comment by IDoytchinov** [comment]
Thanks for the kind answer @glorialulu  !! :)
