### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by MiloshBogdanovic** [glorialulu/wmoc#23]
* tsnet version: 0.2.2
* Python version: 3.7.9
* Operating System: Windows 10

### Description

I am having AttributeError: can't set attribute when trying to import network transient model "Tnet1" shown in example. As i read from docs leak_status its nodes read only property and can not be changed. Any idea how to fix this?

### What I Did

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Wes Trade\PycharmProjects\pythonProject\TSNet-test\env\lib\site-packages\tsnet\network\model.py", line 59, in __init__
    node.leak_status = False
AttributeError: can't set attribute
```

**Comment by glorialulu** [comment]
This is a compatibility issue with the latest WNTR 0.3.1. This will be fixed soon. Meanwhile, consider using previous WNTR versions by `pip install wntr=0.3.0`

**Comment by glorialulu** [comment]
This is a known compatibility issue with the new WNTR release. It will be fixed in the next release. Meanwhile, please consider installing the previous WNTR version (WNTR 0.3.0) as a quick workaround by:

```
pip uninstall wntr
pip install wntr=0.3.0

```
