### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by rxm562** [glorialulu/wmoc#25]
* tsnet version: 0.2.2
* Python version: python3.9
* Operating System: Mac OS BigSur

### Description

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/zc/l6fqnfjd14sg421vzg4ys2900000gn/T/ipykernel_9351/3006219835.py in <module>
----> 1 tm = tsnet.network.TransientModel(inp_file)

~/opt/anaconda3/lib/python3.9/site-packages/tsnet/network/model.py in __init__(self, inp_file)
     57         for _, node in self.nodes():
     58             node.id = i
---> 59             node.leak_status = False
     60             node.burst_status = False
     61             node.blockage_status = False

AttributeError: can't set attribute

### What I Did

I tried to run the example but unable to load the .inp file. Getting AttributeError
```
import tsnet
inp_file = 'Network/Tnet1.inp'
tm = tsnet.network.TransientModel(inp_file)
```

**Comment by spyrosmichas** [comment]
Had similar issue. Use a Python 3.7 environment.

**Comment by glorialulu** [comment]
This is a known compatibility issue. Please refer to #23

**Comment by rxm562** [comment]
Thanks, installing wntr 0.3.0 unable to recognize wntr.simulator. Finally I was able to solve it by installing the python 3.7 environment.
