### ISSUE TITLE
reproduce Tnet0 example plots

### ISSUE THREAD

**Issue by Nathan-Becker** [glorialulu/wmoc#3]
* tsnet version: latest master
* Python version: 3.7.4
* Operating System: Mac OS X

### Description

I'm experimenting with this software, trying to understand how to setup some simple transient models, consisting of a reservoir, a few pipes, and a valve. My goal is to model the transients upon either opening or closing the valve.

### What I Did

I tried to reproduce Figs. A and B of Tnet0 shown here: https://tsnet.readthedocs.io/en/latest/validation.html

I am able to reproduce Fig. B but not Fig. A. When I plot the flow-rate, I see a steady sinusoid pattern with no apparent damping, unlike the plot in the link above, which shows rapid flow-rate decay in the first 2 seconds.

Also, why does the flow-rate and pressure head ring for such a long time? I tried increasing the simulation period to 600s and there is very little damping of the pressure head.

Here is the code I used:
```
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
import tsnet


# Open an example network and create a transient model
inp_file = 'Tnet0.inp'
tm = tsnet.network.TransientModel(inp_file)

# Set wavespeed
tm.set_wavespeed(1200.) # m/s

# Set time options
dt = 0.01
tf = 60   # simulation period [s]
tm.set_time(tf,dt)

# Set valve closure
tc = 2 # valve closure period [s]
ts = 0 # valve closure start time [s]
se = 0 # end open percentage [s]
m = 1 # closure constant [dimensionless]
valve_op = [tc,ts,se,m]
tm.valve_closure('3',valve_op)

# Initialize steady state simulation
t0 = 0. # initialize the simulation at 0 [s]
engine = 'DD' # demand driven simulator
tm = tsnet.simulation.Initializer(tm, t0, engine)

# Transient simulation
results_obj = 'Tnet0' # name of the object for saving simulation results
friction = 'steady'
tm1 = tsnet.simulation.MOCSimulator(tm, results_obj, friction)

# Get head at junction between the pipes
node = '2'
head1 = tm1.get_node(node).head

# Get flow-rate in pipe 2
fr = tm1.get_link('2').start_node_flowrate

# Prep plotting
t1 = tm1.simulation_timestamps
fig = plt.figure(figsize=(8,5), dpi=80, facecolor='w', edgecolor='k')

# Plot flow-rate
plt.plot(t1, fr, 'k',label='steady', linewidth=2.5)
plt.ylabel("flow-rate [m^3/s]")
plt.xlim([t1[0],t1[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('a.png')

# Plot head
plt.clf()
plt.plot(t1, head1, 'k',label='steady', linewidth=2.5)
plt.ylabel("Pressure Head [m]")
plt.xlim([t1[0],t1[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('b.png')
```

**Comment by glorialulu** [comment]
Hi Nathan, 

Thanks for trying out TSNet. To answer your two question:

1. Figs. A of Tnet0 shows the flowrate at the valve, i.e., the end node of pipe 2, while your codes plot the flowrate at the start node of pipe 2.

2. The lack of damping in pressure and flowrate is partially due to the choice of friction model, which is steady friction model in your codes. This model only accounts for the head loss in form of roghness*head^2, and the roughness is set to be fairly small in this example (0.02). The unsteady frictrion model can introduce additional damping.
Another reason is due to the fact that Tnet0 is a very simple network, so the pressure wave essentially bounces back and forward between the two ends.

Best,
Lu

**Comment by Nathan-Becker** [comment]
Ah, thanks very much. Yes, I see that if I use
```
fr = tm1.get_link('2').end_node_flowrate
```
then it reproduces the figure in the docs.

I also see that if I change to
```
friction = 'unsteady'
```
then the behavior damps more.

I really appreciate your help and thanks for building this code. I might have further questions as I dig deeper.

**Comment by glorialulu** [comment]
Sure, feel free to post any issues or questions here.
