### ISSUE TITLE
valve warnings and pump instability

### ISSUE THREAD

**Issue by Nathan-Becker** [glorialulu/wmoc#4]
* tsnet version: latest master
* Python version: 3.7.4
* Operating System: Mac OSX

### Description

I'm trying to model transients after opening a valve with flow being driven by a pump.

The code below seems to work and give plausible results. However, I have a few issues:

1. Even though I tried to set the valve status to LinkStatus.Closed in 2 places, I still get a warning that says, "model.py:318: UserWarning: Valve valve is already open in its initial setting. The initial setting has been changed to closed to perform the opening."  How do I properly initialize the valve to closed at the start? Also, can you explain what the valve 'setting' parameter does? I haven't been able to find any documentation on that.

2. I would like to be able to adjust the maximum pressure from the pump. But I find that almost any adjustment of the pump curves gives totally crazy results. For example, if I change the first point in the curve to psi_to_m(41) instead of psi_to_m(40), the outputs from the simulation blow up. How can I stabilize this?

### What I Did

Here is the code

```
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
import wntr
import tsnet


def gpm_to_m3s(gpm):
    return gpm/(60*264.172)

def m3s_to_gpm(m3s):
    return m3s*(60*264.172)

def m_to_psi(m):
    return m*1.4219702063247

def psi_to_m(psi):
    return psi/1.4219702063247


# New network
wn = wntr.network.WaterNetworkModel()

# Add components
wn.add_reservoir('res', base_head=0, coordinates=(-100,0))
wn.add_junction('in', coordinates=(-20,0))
wn.add_pipe('source', start_node_name='res', end_node_name='in', length=80, diameter=0.03175*2)
wn.add_junction('ref', coordinates=(0,0))
pumpcurve = []
pumpcurve.append((gpm_to_m3s(0),psi_to_m(40)))
pumpcurve.append((gpm_to_m3s(1),psi_to_m(30)))
pumpcurve.append((gpm_to_m3s(2),psi_to_m(20)))
wn.add_curve('pumpcurve', 'HEAD', pumpcurve)
wn.add_pump(name='supply', start_node_name='in', end_node_name='ref', pump_type='HEAD', pump_parameter='pumpcurve')
wn.add_reservoir('atmos', base_head=psi_to_m(0), coordinates=(40,0))
wn.add_junction('before_valve', coordinates=(20,0))
wn.add_pipe('to_valve', start_node_name='ref', end_node_name='before_valve', length=100, diameter=0.03175)
wn.add_junction('after_valve', base_demand=0, coordinates=(20,0))
wn.add_valve('valve', start_node_name='before_valve', end_node_name='after_valve', valve_type='FCV', setting=0)
wn.get_link('valve').status = wntr.network.elements.LinkStatus.Closed
wn.add_reservoir('atmos', base_head=0, coordinates=(40,0))
wn.add_pipe('out', start_node_name='after_valve', end_node_name='atmos', length=10, diameter=0.03175/3)

# Build EPANET file
wn.write_inpfile('simp.inp')

# Construct transient model 
tm = tsnet.network.TransientModel('simp.inp')
tm.get_link('valve').status = wntr.network.elements.LinkStatus.Closed

# Set wavespeed
tm.set_wavespeed(1200.) # m/s

# Set time options
tf = 5   # simulation period [s]
tm.set_time(tf)

# Set valve opening 
tc = 0.1 # valve opening period [s]
ts = 0.5 # valve opening start time [s]
se = 0.1 # end open percentage [s]
m = 1 # open constant [dimensionless]
tm.valve_opening('valve',[tc,ts,se,m])

# Initialize steady state simulation
t0=0
tm = tsnet.simulation.Initializer(tm,t0,'DD')

# Transient simulation
results_obj = 'simpres'
friction = 'unsteady'
tm = tsnet.simulation.MOCSimulator(tm, results_obj, friction)

# Gather results
t = tm.simulation_timestamps
ref_head = tm.get_node('ref').head
output_head = tm.get_node('after_valve').head
ref_flow_rate = tm.get_link('to_valve').start_node_flowrate
output_flow_rate = tm.get_link('out').end_node_flowrate

# Prep plotting
fig = plt.figure(figsize=(8,5), dpi=80, facecolor='w', edgecolor='k')

# Plot flow-rates
plt.plot(t, m3s_to_gpm(ref_flow_rate), 'k', label='ref', linewidth=1.5)
plt.plot(t, m3s_to_gpm(output_flow_rate), 'r--', label='output', linewidth=1.5)
plt.ylabel("flow-rate [gpm]")
plt.xlim([t[0],t[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('flowrate.png')
    
# Plot heads
plt.clf()
plt.plot(t, m_to_psi(ref_head), 'k', label='ref', linewidth=1.5)
plt.plot(t, m_to_psi(output_head), 'r--', label='output', linewidth=1.5)
plt.ylabel("Pressure [PSI]")
plt.xlim([t[0],t[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('pressure.png')
```

**Comment by glorialulu** [comment]
For valves:
- set the initial status for valves using:
`valve.initial_status.name == 'Open' #or 'Closed', or 'Active'`

- valve setting parameters are defined according to EPANet 2 manual. Please refer to page 176 of 
> Rossman, L. A. (2000). EPANET 2: users manual.

btw, these functions are supported by WNTRpackage, not TSNet

For pumps:
- The pump curve has to be concave. If you change 40 to 41, the curve then becomes convex, which is the reason why the results do not make sense. However, you can change  40 to 39, or any other values as long as the pump curve is still concave.

**Comment by Nathan-Becker** [comment]
Thanks very much for the reference- very informative.

Yes, I found that the valve warning went away using:
```
wn.get_link('valve').initial_status = wntr.network.elements.LinkStatus.Closed
```

For the pump, I don't see in the docs where it explicitly says that the curve must be concave. But, that does seem to be true. With more fiddling, I am able to find other usable pump curves using the criteria that
```
wn.get_link('supply').get_head_curve_coefficients()[2] >= 1
```
Thanks again for your help. I think I will have another question soon, as I am trying to add multiple valves and getting some unexpected results.

**Comment by Nathan-Becker** [comment]
Does the transient simulator default to every valve opening at t=0? I'm finding that if I omit the line that defines the valve opening:
```
tm.valve_opening('valve',[tc,ts,se,m])
```
then the valve opens at t=0, even when I explicitly define the network with the valve initial_status='Closed'. I'm expecting that if I omit the valve opening, then the valve should never open and the pressure should remain constant and flow-rate nearly zero.
I do find that if I set the valve opening to start at a time after the end of the simulation, then the valve never opens (as expected) and the solution is constant for pressure and nearly zero for flow-rate. When I do this workaround, I see a small nonzero flow-rate for a brief period of time, about 0.5 sec, at the beginning of the simulation. Perhaps this is just numerical noise?

**Comment by glorialulu** [comment]
I opened a new issue for this and will look into the codes to find out why.
